export {
  Rect as SvgRect,
  Circle as SvgCircle,
  Ellipse as SvgEllipse,
  Line as SvgLine,
  Polygon as SvgPolygon,
  Polyline as SvgPolyline,
  Path as SvgPath,
  Text as SvgText,
  TSpan as SvgTSpan,
  TextPath as SvgTextPath,
  G as SvgG,
  Use as SvgUse,
  Symbol as SvgSymbol,
  Defs as SvgDefs,
  Image as SvgImage,
  ClipPath as SvgClipPath,
  LinearGradient as SvgLinearGradient,
  RadialGradient as SvgRadialGradient,
  Mask as SvgMask,
  Pattern as SvgPattern,
  Marker as SvgMarker,
  ForeignObject as SvgForeignObject,
} from 'react-native-svg'

export * from 'react-native-svg'
